---
name: Build Image

env:
  SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
  TENANT_ID: ${{secrets.TENANT_ID}}
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
"on":
  push:
    branches: [main]

jobs:
  image_creation_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Hashicorp Packer
        uses: hashicorp-contrib/setup-packer@v3
        with:
          packer-version: 1.11.0

      - name: Setting packer logs to Verbose
        run: export PACKER_LOG=1

      - name: Download Packer plugin libraries
        run: packer init image.pkr.hcl

      - name: Packer template validation
        run: packer validate image.pkr.hcl 

      - name: Building Packer Template
        run: |
          packer build -force \
            -var "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" \
            -var "CLIENT_ID=${{secrets.CLIENT_ID}}" \
            -var "TENANT_ID=${{secrets.TENANT_ID}}" \
            -var "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" \
            image.pkr.hcl